### ISSUE TITLE
setting redshift on custom model

### ISSUE THREAD

**Issue by kilianbreathnach** [astropy/halotools#643] opened 2017-01-19 17:51 UTC
In making a custom model with a `HodModelFactory` instance, there doesn't seem to be a simple, clean way of providing a redshift to the constructor out of the box. This would be helpful for my use of halotools and I imagine it would be useful for others too.

The `self.set_model_redshift()` method which is called during `__init__()` searches through `self.model_dictionary` for objects with a `redshift` attribute. So, as of now, the only way to have a non-default redshift initialised in a `HodModelFactory` instance is by providing an instance of some object with a redshift attribute to an arbitrary keyword argument (as a hack). This is obviously built this way to "inherit" the redshift of the `baseline_model_instance` but is a somewhat tedious avenue if you never needed a baseline model, not to mention the circular problem of getting a custom redshift in your baseline model in the first place!

I'd suggest including an optional `redshift` keyword, since many of the `halotools` constructors have this. I attempted this at first and ran into the problem that the keyword is assumed to be a model feature or galaxy type:

> The ``_infer_gal_type_and_feature_name`` method was unable to identify
> the name of your galaxy population from the ``redshift`` key of the model_dictionary.
> If you are modeling a population whose name is neither ``centrals`` nor ``satellites``,
> then you must provide a ``gal_type_list`` keyword argument to 
> the constructor of the HodModelFactory.

I'd be happy to provide a pull request that enables this functionality by avoiding the error in the `model_calling_sequence` and sending a `redshift` kwarg value to the `set_model_redshift()` method to replace any baseline or default values.

As of now the simple solution with `halotools` is obviously:

```
model = HodModelFactory(**kwargs)
model.redshift = redshift
```

**Comment by aphearin** [comment] 2017-01-20 21:56
@kilianbreathnach - I think I might not quite follow, correct me if I'm wrong, but isn't it the case that if *any* of the component model instances have a `redshift` attribute, then this redshift is guaranteed to get bound to the composite model object created by `HodModelFactory`? At least, I'm sure that was the intention. If I'm right about that, then whenever you build a custom composite model, don't you just need to make sure that one of the components has a `redshift` bound to it? Or do I misunderstand what you're trying to do?

**Comment by aphearin** [comment] 2017-01-31 12:05
Closing this after merging #644. @kilianbreathnach - please reopen if the issue is not resolved.

**Closed by aphearin** 2017-01-31 12:05 UTC
Labels: empirical-models, feature request
