### ISSUE TITLE
Bug in 2PCF as a function of s and mu

### ISSUE THREAD

**Issue by johannesulf** [astropy/halotools#649] opened 2017-01-26 23:21 UTC
@aphearin As discussed earlier, there seems to be something wrong with s_mu_tpcf. For example, calculating the tpcf for randoms results in non-zero values.

```
from halotools.mock_observables import s_mu_tpcf, tpcf_multipole, rp_pi_tpcf

Npts = 300000
Lbox = 250.

x = np.random.uniform(0, Lbox, Npts)
y = np.random.uniform(0, Lbox, Npts)
z = np.random.uniform(0, Lbox, Npts)
pos = np.vstack((x,y,z)).T

s_bins = np.logspace(-1, 1, 50)
mu_bins = np.linspace(0, 1, 50)
xi = s_mu_tpcf(pos, s_bins, mu_bins, period=Lbox, num_threads='max')
```

Here, xi is not zero/noise. I believe the error boils down to a line in the npairs_s_mu_engine. I think mu is calculated incorrectly. It's calculated as if it was cos(theta), but we defined it as sin(theta).

So
`mu = sqrt(dz_sq)/s`
should be
`mu = sqrt(s*s - dz_sq)/s`
or something similar. With that change I get zero/noise for randoms. Please tell me what you think about that. By the way, my PR#623 didn't change the above mentioned line.

**Comment by aphearin** [comment] 2017-01-26 23:32
Tagging @duncandc who wrote many of these internals.

**Comment by aphearin** [comment] 2017-01-27 14:04
I can't recall why @duncandc used an alternative convention of sin vs. cos, @johannesulf. Before submitting a PR with your proposed change, let's let him weigh in to make sure there won't be additional upstream consequences.

**Comment by johannesulf** [comment] 2017-01-27 15:55
I did some more science tests than just the randoms. My original intend was to reproduce the redshift-space clustering in Guo et al. 2015 (https://arxiv.org/abs/1505.07861). With the original halotools code and the Zheng07 HOD model the quadropole and hexadecapole moments look nothing like the ones in Guo et al. 2015 (Figure 2 and 3). However, with my proposed fix they look very close, 
both qualitatively and quantitatively. I attached a small notebook to do these kind of calculations.

[Calculate_Clustering_Demo.ipynb.zip](https://github.com/astropy/halotools/files/735646/Calculate_Clustering_Demo.ipynb.zip)

**Comment by duncandc** [comment] 2017-01-27 15:57
This all looks good to me.  I saw go ahead and merge.

**Comment by aphearin** [comment] 2017-01-27 16:23
Your notebook is a compelling demonstration @johannesulf. Could you submit a PR with the change you have implemented it?

**Comment by johannesulf** [comment] 2017-01-27 16:33
Sure thing! I'll do it later today.

**Comment by aphearin** [comment] 2017-01-27 16:40
Great, thanks. If you can think of a reasonable regression test to include, that would be ideal. But if you don't want to bother, I can just submit my own PR against yours after you submit yours. Either way, as part of your PR, please add your name to the alphabetized list of contributors in the following documentation file: `halotools/docs/quickstart_and_tutorials/development/contributors.rst`

**Comment by johannesulf** [comment] 2017-01-27 19:55
I submitted the PR addressing the issue in the pair counter. The 0th order check that randoms don't create a signal now works. However, I'm not quite convinced that everything in the multipole calculation works correctly now. The multipole moments are all suspiciously low by around a factor of 2. I'll investigate this further.

**Comment by surhudm** [comment] 2017-01-28 04:51
Hi all,

Can you clarify what is the convention used?

Typically mu is the cosine of the angle between the line of sight and s.
Isn't it correct that dz is along the line of sight?

So if dz=s, shouldn't the angle be zero and mu=1?

Cheers,
Surhud

**Comment by johannesulf** [comment] 2017-01-28 05:02
@surhudm The internals of s_mu_tpcf are a bit confusing. You enter the mu values using the usual convention, mu = cos(theta), like you wrote. However, internally it converts it into mu = sin(theta). I don't entirely understand why that needed to be done. But you can clearly see it written out in halotools/mock_observables/two_point_clustering/s_mu_tpcf.py line 412.

```
# work with the sine of the angle between s and the LOS.  Only using cosine as the
# input because of convention.  sin(theta_los) increases as theta_los increases, which
# is required in order to get the pair counter to work.
theta = np.arccos(mu_bins)
mu_bins = np.sin(theta)[::-1]  # must be increasing, remember to reverse result.
```

**Comment by surhudm** [comment] 2017-01-28 06:18
I see. I think the code needs to use a different variable name then in that
place to avoid such a confusion. Should thr variable be changed from mu to
muprime or something like that?

Surhud


On Sat, Jan 28, 2017 at 14:02 Johannes Lange <notifications@github.com>
wrote:

@surhudm <https://github.com/surhudm> The internals of s_mu_tpcf are a bit
confusing. You enter the mu values using the usual convention, mu =
cos(theta), like you wrote. However, internally it converts it into mu =
sin(theta). I don't entirely understand why that needed to be done. But you
can clearly see it written out in
halotools/mock_observables/two_point_clustering/s_mu_tpcf.py line 412.

# work with the sine of the angle between s and the LOS.  Only using
cosine as the
# input because of convention.  sin(theta_los) increases as theta_los
increases, which
# is required in order to get the pair counter to work.
theta = np.arccos(mu_bins)
mu_bins = np.sin(theta)[::-1]  # must be increasing, remember to reverse result.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/astropy/halotools/issues/649#issuecomment-275827802>,
or mute the thread

**Comment by aphearin** [comment] 2017-01-31 12:16
I went ahead and merged this in since it does resolve the issue. The #651 could end up being related, or that could be simply a failure due to the Legendre polynomial implementation. I will resolve #653 in a separate PR.

**Closed by aphearin** 2017-01-31 12:16 UTC
Labels: bug
