### ISSUE TITLE
HOD Population (possibly) implemented incorrectly. 

### ISSUE THREAD

**Issue by mclaughlin6464** [astropy/halotools#543] opened 2016-06-05 01:21 UTC
I've been using the Zheng07 HOD and I noticed something that may be inconsistent with the literature. If, for example, I set the mMin for the Zheng07Cens very high (~10**16 Msun) there'll be no central galaxies in my mock, but the amount of satellites will be unchanged. However, if you look at equation 7 in [this paper](http://arxiv.org/abs/1005.2413) we see that if N_c - > 0, N_tot -> 0. Is this an intentional design decision to not coincide with this?

**Comment by aphearin** [comment] 2016-06-05 12:39
Yes, this is the intended default behavior. It sounds like you want to use the `modulate_with_cen_occ` feature, described in http://halotools.readthedocs.io/en/latest/api/halotools.empirical_models.Zheng07Sats.html#halotools.empirical_models.Zheng07Sats. 

All composite model keywords automatically get passed to on the component model through the factory. So, 

model = PrebuiltHodModelFactory('zheng07', modulate_with_cenocc=True)

**Comment by mclaughlin6464** [comment] 2016-06-05 16:53
That looks exactly like what I need. Thank you!

**Comment by aphearin** [comment] 2016-06-05 17:04
No problem. Let me know if you have any tips for making this feature more discoverable.

**Comment by surhudm** [comment] 2016-06-05 19:01
Shouldn't the default in Zheng07Sats be modulate_with_cenocc=True, since
the definition in Zheng07 does modulate with central occupation? I think
that is what Sean was asking.

**Comment by aphearin** [comment] 2016-06-05 19:55
I considered that @surhudm and @mclaughlin6464. But I now have multiple different users actively using PrebuiltHodModelFactory('zheng07'), so I'm hesitant to silently change the default behavior. I guess I considered the documentation sufficiently clear to not worry about this, but maybe you two see it differently?

**Comment by surhudm** [comment] 2016-06-05 20:16
Perhaps the problem is associating the name of this function with Zheng 07
(instead of calling it just some truncated ,power law satellite halo
occupation). I can easily imagine the same users writing in a paper that
they used the Zheng 07 HOD without actually specifying that this HOD was
not tied to <Nc>(M) as in the original paper. If they correctly state in
the paper what they use its ok, if not, then its an issue.

**Comment by aphearin** [comment] 2016-06-05 20:20
So to recap:

1. The advantage of changing default modulate_with_cenocc=True is that this was the choice made in Zheng+07. 
2. The disadvantage of changing is that it's a well-used section of Halotools, and it would rightfully irritate other users if all of a sudden their model starts producing different science results. 

The reason I made an initial request to @mclaughlin6464 for "discoverability" suggestions was because of my concern over (2). 

The reason I didn't consider (1) to be mission-critical in the first place is because I never make any guarantees that you can reproduce a given publication with the corresponding pre-built model. After all, Zheng+07 did not use direct-mock-population, used a different cosmology, halo mass definition, etc. On a slightly more editorial note, I also consider the Zheng+07 choice to multiply satellite occupation moment by the central moment to be purely ad hoc, which is why there is this option to use it or ignore it. 

## Option 1
Improve documentation and make no changes to default behavior. For this I would need suggestions, I'm not sure how to make it any more clear and I'm too close to the code to know what the new-user entry points are. 

## Option 2
Elevate `modulate_with_cenocc` to a mandatory positional argument. This will break backwards compatibility, but it will at least do so in a way that is not silent. 

## Option 3
Change the default behavior, but automatically raise a warning anytime anyone instantiates the class with 
modulate_with_cenocc set to `True`, explicitly stating that the `v0.1` default value has changed. 

Other users of PrebuiltHodModelFactory('zheng07') may wish to weigh in, so I'm tagging @andrew-zentner, @mjvakili, @changhoonhahn.

Also tagging @eteq, who has lots of experience navigating backwards compatibility issues. @eteq - this is the first time such an issue has come up, so it would be helpful for you to weigh in about protocol for how this kind of thing is handled in astropy.

**Comment by mclaughlin6464** [comment] 2016-06-05 22:36
I'd say option 1 is best. I was under the assumption that this was already happening behind the scenes. [This page](http://halotools.readthedocs.io/en/latest/quickstart_and_tutorials/tutorials/model_building/preloaded_models/zheng07_composite_model.html) of the docs makes no mention of this feature and was my primary reference point. It should be listed their in addition to the docstring.

**Comment by manodeep** [comment] 2016-06-05 22:42
@aphearin I agree with @surhudm -- the name `Zheng07` would imply that the underlying HOD is done as was presented in the paper. What I expect is people will use `halotools` as a tool/blackbox, then it is best to be in accordance what users might expect. 

To me, option 3 seems the right way forward.

**Comment by aphearin** [comment] 2016-06-05 23:09
@mclaughlin6464 - glad to hear you were using the Zheng+07 page of the docs as your basis. I completely agree that, at a minimum, this detail should be included in that page of the docs. That's an omission, and I'll fix that regardless. 

@manodeep - thanks also for weighing in. I think it's worth pointing out out that @mclaughlin6464 discovered the most relevant section of the docs entirely on his own, with no guidance whatsoever from me. If that section had been properly documented, the issue would never have come up, so I think his suggestion is reasonable. However, I'd still like to hear from the other users of this section of the code before deciding.

**Comment by mjvakili** [comment] 2016-06-05 23:35
How about adding to the Zheng07 page of the docs a few lines that describes how the Prebuilt model is built using something like this:

HodModelFactory(cens_occ_model, cens_prof_model, sats_occ_model, sats_prof_model),

where in the arguments of sats_occ_model (here Zheng07Sats), one can set "modulate_with_cenocc" to True or False.

**Comment by aphearin** [comment] 2016-06-09 12:27
Ok, thanks for weighing in everyone. I decided to go with option 3, since both @mjvakili and @mclaughlin6464 have been using this particular section of the code and independently suggested that modifying the docs would be sufficient. So #552 calls explicit attention to the fact that in order to strictly reproduce Zheng+07 results, it is necessary to set `modulate_with_cenocc` to True. That PR also includes lots more hyperlinks added to the code so that the composite model tutorials are more discoverable. I will close this issue now, but feel free to open it again if you think these changes are not sufficient.

**Closed by aphearin** 2016-06-09 12:27 UTC
Labels: documentation
